export default function MyObject() {
  return [
    {
      class: "metal",
      id: "watch",
      link: "images/watch.gif",
      top: null,
      left: null,
    },
    {
      class: "metal",
      id: "cross",
      link: "images/cross.gif",
      top: null,
      left: null,
    },
    {
      class: "metal",
      id: "diamond-ring",
      link: "images/diamond-ring.gif",
      top: null,
      left: null,
    },
    {
      class: "metal",
      id: "necklace",
      link: "images/necklace.gif",
      top: null,
      left: null,
    },
    {
      class: "metal",
      id: "bell",
      link: "images/bell.gif",
      top: null,
      left: null,
    },
    {
      class: "metal",
      id: "padlock",
      link: "images/padlock.gif",
      top: null,
      left: null,
    },
    {
      class: "metal",
      id: "gold-ring",
      link: "images/gold-ring.gif",
      top: null,
      left: null,
    },
    {
      class: "metal",
      id: "cellphone",
      link: "images/cellphone.gif",
      top: null,
      left: null,
    },
    {
      class: "metal",
      id: "coin",
      link: "images/coin.gif",
      top: null,
      left: null,
    },
    {
      class: "metal",
      id: "gold",
      link: "images/gold.gif",
      top: null,
      left: null,
    },
    {
      class: "metal",
      id: "monitor",
      link: "images/monitor.gif",
      top: null,
      left: null,
    },
    {
      class: "metal",
      id: "steel",
      link: "images/steel.gif",
      top: null,
      left: null,
    },
    {
      class: "metal",
      id: "key",
      link: "images/key.gif",
      top: null,
      left: null,
    },
    {
      class: "metal",
      id: "magnet",
      link: "images/magnet.gif",
      top: null,
      left: null,
    },
    {
      class: "metal",
      id: "sword",
      link: "images/sword.gif",
      top: null,
      left: null,
    },

    {
      class: "non-metal",
      id: "bottle",
      link: "images/plastic-bottle.gif",
      top: null,
      left: null,
    },
    {
      class: "non-metal",
      id: "t-shirt",
      link: "images/t-shirt.gif",
      top: null,
      left: null,
    },
    {
      class: "non-metal",
      id: "sunglasses",
      link: "images/sunglasses.gif",
      top: null,
      left: null,
    },
    {
      class: "non-metal",
      id: "rubics-cube",
      link: "images/rubics-cube.gif",
      top: null,
      left: null,
    },
    {
      class: "non-metal",
      id: "short",
      link: "images/short.gif",
      top: null,
      left: null,
    },
    {
      class: "non-metal",
      id: "shoes",
      link: "images/shoes.gif",
      top: null,
      left: null,
    },
    {
      class: "non-metal",
      id: "slippers",
      link: "images/slippers.gif",
      top: null,
      left: null,
    },
    {
      class: "non-metal",
      id: "food",
      link: "images/food.gif",
      top: null,
      left: null,
    },
    {
      class: "non-metal",
      id: "cap",
      link: "images/cap.gif",
      top: null,
      left: null,
    },
    {
      class: "non-metal",
      id: "cat",
      link: "images/cat.gif",
      top: null,
      left: null,
    },
    {
      class: "non-metal",
      id: "dog",
      link: "images/dog.gif",
      top: null,
      left: null,
    },
    {
      class: "non-metal",
      id: "book",
      link: "images/Book.gif",
      top: null,
      left: null,
    },
    {
      class: "non-metal",
      id: "pillow",
      link: "images/pillow.gif",
      top: null,
      left: null,
    },
    {
      class: "non-metal",
      id: "chair",
      link: "images/chair.gif",
      top: null,
      left: null,
    },
    {
      class: "non-metal",
      id: "mouse",
      link: "images/mouse.gif",
      top: null,
      left: null,
    },
  ];
}
